version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calorie_tracker_Bdd
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./TpCalorie
    container_name: tpcalorie-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/calorie_tracker_Bdd
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - app-network

  frontend:
    build: ./calorie-tracker
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
